package test;

import org.openqa.selenium.By;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.Set;

/**
 * Selenium Java Test for Salesforce Lead Creation
 * Test Case: TC127 - Verify successful Lead creation with required fields
 */
public class TC127 {

    private WebDriver driver;
    private WebDriverWait wait;

    @BeforeMethod
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--window-size=1920,1080");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--no-sandbox");

        driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(120));
        driver.manage().window().maximize();

        wait = new WebDriverWait(driver, Duration.ofSeconds(60));

        // 🔐 Step 1: Open Salesforce domain FIRST
        driver.get("https://login.salesforce.com");

        // 🔐 Step 2: Inject cookies (from storageState.json via MCP)
        injectSalesforceCookies();

        // 🔐 Step 3: Refresh to apply session
        driver.navigate().refresh();
    }

    @Test
    public void testLeadCreation() {

        // Navigate directly to Lightning Home
        driver.get("https://orgfarm-5694adb5bf-dev-ed.develop.lightning.force.com/lightning/page/home");

        // ---------------- APP LAUNCHER ----------------
        WebElement appLauncher = wait.until(
                ExpectedConditions.elementToBeClickable(By.cssSelector("button[title='App Launcher']"))
        );
        appLauncher.click();

        WebElement viewAll = wait.until(
                ExpectedConditions.elementToBeClickable(By.xpath("//button[text()='View All']"))
        );
        viewAll.click();

        WebElement salesApp = wait.until(
                ExpectedConditions.elementToBeClickable(
                        By.cssSelector("one-app-launcher-app-tile[data-name='Sales']")
                )
        );
        salesApp.click();

        // ---------------- LEADS ----------------
        WebElement leadsTab = wait.until(
                ExpectedConditions.elementToBeClickable(By.cssSelector("a[title='Leads']"))
        );
        leadsTab.click();

        WebElement newButton = wait.until(
                ExpectedConditions.elementToBeClickable(By.cssSelector("button[name='New']"))
        );

        ((JavascriptExecutor) driver).executeScript("arguments[0].click();", newButton);

        // ---------------- FILL REQUIRED FIELDS ----------------
        WebElement lastName = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.xpath("//label[text()='Last Name']/following::input[1]")
                )
        );
        lastName.sendKeys("SeleniumJavaLead");

        WebElement company = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.xpath("//label[text()='Company']/following::input[1]")
                )
        );
        company.sendKeys("Selenium Java Inc");

        WebElement saveButton = wait.until(
                ExpectedConditions.elementToBeClickable(By.cssSelector("button[name='SaveEdit']"))
        );
        saveButton.click();

        // ---------------- VERIFY TOAST ----------------
        WebElement toast = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div[role='alert']"))
        );

        Assert.assertTrue(
                toast.getText().contains("Lead"),
                "Expected Lead creation toast, but got: " + toast.getText()
        );
    }

    /**
     * Inject Salesforce cookies extracted from storageState.json
     * (Generated by MCP — not Playwright at runtime)
     */
    private void injectSalesforceCookies() {
        Set<Cookie> cookiesFromMCP = SalesforceCookieStore.getCookies();

        for (Cookie cookie : cookiesFromMCP)
